name: slack-sansio-doc
dependencies:
  - python=3.7
  - pip:
    - aiohttp==3.4.4
    - alabaster==0.7.12
    - appdirs==1.4.3
    - asks==2.2.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - asynctest==0.12.2
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - Babel==2.6.0
    - black==18.9b0
    - certifi==2018.10.15
    - chardet==3.0.4
    - Click==7.0
    - coverage==4.5.2
    - curio==0.9
    - docutils==0.14
    - filelock==3.0.10
    - flake8==3.6.0
    - h11==0.8.1
    - idna==2.7
    - imagesize==1.1.0
    - isort==4.3.4
    - Jinja2==2.10
    - MarkupSafe==1.1.0
    - mccabe==0.6.1
    - mock==2.0.0
    - more-itertools==4.3.0
    - multidict==4.5.0
    - multio==0.2.4
    - mypy==0.641
    - mypy-extensions==0.4.1
    - outcome==1.0.0
    - packaging==18.0
    - pbr==5.1.1
    - pluggy==0.8.0
    - py==1.7.0
    - pycodestyle==2.4.0
    - pyflakes==2.0.0
    - Pygments==2.2.0
    - pyparsing==2.3.0
    - pytest==4.0.0
    - pytest-asyncio==0.9.0
    - pytest-cov==2.6.0
    - pytest-cover==3.0.0
    - pytest-coverage==0.0
    - pytz==2018.7
    - requests==2.20.1
    - six==1.11.0
    - sniffio==1.0.0
    - snowballstemmer==1.2.1
    - sortedcontainers==2.0.5
    - Sphinx==1.8.2
    - sphinxcontrib-asyncio==0.2.0
    - sphinxcontrib-websupport==1.1.0
    - toml==0.10.0
    - tox==3.5.3
    - trio==0.9.0
    - typed-ast==1.1.0
    - urllib3==1.24.1
    - virtualenv==16.1.0
    - websocket-client==0.54.0
    - yarl==1.2.6
